#!/bin/bash
# Two monitors, secondary on the right.

# connected_displays can look like (normally defined in ~/.profile):
# connected_displays() { xrandr --listmonitors | tail -n 1 | cut -d ' ' -f 6; }

# best_connected OUT1 OUT2 ...
# Return the first connected output from the input list
best_connected()
{
    CONNECTED_OUTPUTS=$(connected_displays)
    CANDIDATE_OUTPUTS="$@"
    for OUTPUT in "$CONNECTED_OUTPUTS"; do
        if [[ "$CANDIDATE_OUTPUTS" =~ "$OUTPUT" ]]; then
            # If $OUTPUT in $CANDIDATE_OUTPUTS, bash regular expression
            echo "$OUTPUT"
            return 1
        fi
    done
    return 0
}

HOST=$(hostname -f)

if [[ "$HOST" = pcgael ]]; then
    # eDP1 = laptop screen
    PRIMARY=eDP1
    RIGHT=$(best_connected HDMI3 DP1 DP2 VGA1 HDMI1 HDMI2)
    OFF=("VIRTUAL1" "DP1" "DP2" "VGA1" "HDMI1" "HDMI2" "HDMI3")
elif [[ "$HOST" = pcgael2 ]]; then
    PRIMARY=eDP1
    RIGHT=$(best_connected HDMI3 DP1 DP2 VGA1 HDMI1 HDMI2)
    OFF=("VIRTUAL1" "DP1" "DP2" "VGA1" "HDMI1" "HDMI2" "HDMI3")
elif [[ "$HOST" = pcgael3 ]]; then
    PRIMARY=eDP1
    RIGHT=HDMI3
    OFF=("VIRTUAL1" "DP2" "DP1" "VGA1" "HDMI2" "HDMI1")
else
    exit 1
fi

for OUTPUT in "${OFF[@]}"; do
    if [[ "$OUTPUT " != "$RIGHT" ]]; then
        xrandr --output "$OUTPUT" --off
    fi
done

if [[ -z "$RIGHT" ]]; then
    xrandr \
        --output "$PRIMARY" --auto --primary
else
    xrandr \
        --output "$PRIMARY" --auto --primary \
        --output "$RIGHT" --auto --right-of "$PRIMARY"
fi
