#!/bin/bash
# Utility functions for display (output, monitor) management.

# Usage: all_outputs_except OUTPUT
all_outputs_except()
{
    EXCLUDE="$1"
    xrandr | grep connected | cut --delimiter=' ' --field=1 | grep -v -e "\<$EXCLUDE\>"
}

# Usage: connected_display
connected_displays()
{
    xrandr | grep -v disconnected | grep connected | cut --delimiter=' ' --field=1
}

# Usage: best_connected OUT1 OUT2 ...
# Return the first connected output from the input list
best_connected()
{
    CONNECTED_OUTPUTS=$(connected_displays)
    CANDIDATE_OUTPUTS="$@"
    for OUTPUT in $CONNECTED_OUTPUTS; do
        if [[ "$CANDIDATE_OUTPUTS" =~ "$OUTPUT" ]]; then
            # If $OUTPUT in $CANDIDATE_OUTPUTS, bash regular expression
            echo "$OUTPUT"
            return 1
        fi
    done
    return 0
}
