#!/bin/zsh

if [[ "$HOST" = pcgael ]]; then
	MOUNT_POINT="/mnt/backup"
	BACKUP_DIR="$MOUNT_POINT"
	PASSPHRASE_FILE="$HOME/.config/duplicity/passphrase.sh"
elif [[ "$HOST" = pcgael3 ]]; then
	MOUNT_POINT="/storage/cesnet-du4-storage"
	BACKUP_DIR="$MOUNT_POINT/home/ecorcgae/VO_storage-tape_tape/backup-pcgael3"
	PASSPHRASE_FILE="$HOME/.config/duplicity/passphrase.sh"
else
	exit 1
fi

# Source the shell script defining PASSPHRASE
if [ -e "$PASSPHRASE_FILE" ]; then
	source "$PASSPHRASE_FILE"
fi

# Mount if not already mounted
DO_UNMOUNT=false
mount | grep "$MOUNT_POINT" > /dev/null
if [ $? = 1 ]; then
	mount "$MOUNT_POINT"
	DO_UNMOUNT=true
fi

if [ -d "$MOUNT_POINT" ]; then
	/usr/bin/duplicity collection-status "file://$BACKUP_DIR"
fi

if $DO_UNMOUNT; then
	umount "$MOUNT_POINT"
fi
