#!/bin/bash

TURN_OFF=1
bluetooth | grep on > /dev/null
if [[ $? != 0 ]]; then
	TURN_OFF=0
	bluetooth on > /dev/null
	sleep 1
fi
ttblue --device=E4:04:39:82:7E:A0 --code=861943 --update-gps
if [[ $TURN_OFF == 0 ]]; then
	bluetooth off > /dev/null
fi
